# name of simulation run, dumps will be under this folder
sim_name: reveal_testing

# absolute path of the directory the nodes will be saved under the simulation name
# don't leave '/' at the end
results_directory: /Users/egeerdogan/desktop/Simbadt/dumps

# simulation events logging level
#   CRITICAL: none
#   WARNING:  only simulator messages (recommended)
#   SUCCESS:  + block generations
#   INFO:     + block receipts
#   DEBUG:    + all protocol messages
log_level: SUCCESS

# how many times to repeat the same simulation
sim_reps: 1

# number of simulation steps
simulation_iters: 30000000

# real-time seconds per simulation step
iter_seconds: 0.1

# expected block interval in iters
block_int_iters: 6000

# outgoing connections per node
connections_per_node: 2

# setup nodes (regions: CH US RU KZ ML CN GE NR VN)
#   at most one entry per region
# miner powers are represented as that region's percent share in global power
nodes:
  - count: 189
    region: CH
    region_mine_power: 70.74

  - count: 1892
    region: US
    region_mine_power: 7.87

  - count: 251
    region: RU
    region_mine_power: 7.50

  - count: 5
    region: KZ
    region_mine_power: 6.71

  - count: 19
    region: ML
    region_mine_power: 4.71

  - count: 316
    region: CN
    region_mine_power: 0.89

  - count: 1769
    region: GE
    region_mine_power: 0.61

  - count: 32
    region: NR
    region_mine_power: 0.52

  - count: 2
    region: VN
    region_mine_power: 0.46

