# name of simulation run, dumps will be under this folder
sim_name: testing

# path of the directory the nodes will be saved under the simulation name
# don't leave '/' at the end
results_directory: /Users/egeerdogan/desktop/Simbadt/dumps

# simulation events logging level
#   CRITICAL: none
#   WARNING:  only simulator messages (recommended)
#   SUCCESS:  + block generations
#   INFO:     + block receipts
#   DEBUG:    + all protocol messages
log_level: SUCCESS

# how many times to repeat the same simulation
sim_reps: 10

# number of simulation steps
sim_iters: 10000

# real-time seconds per simulation step
iter_seconds: 0.1

# expected block interval in iters
block_int_iters: 6000

# maximum block size in bytes
max_block_size: 1000000 # 1 MB

# Transaction modeling detail
# Full:   transactions are propagated over the network; each node has its own mempool
# Simple: nodes share mempool; no transaction propagation over the network
# Null:   no transactions; blocks have tx count and size values sampled from distributions
tx_modeling: Full

# outgoing connections per node
connections_per_node: 2

# number of nodes per region
# set -1 to use the real-world values provided below
nodes_in_each_region: 2

# setup nodes
#   at most one entry per region
# miner powers are represented as that region's percent share in global power
# comment out items to remove region
nodes:
  - count: 189
    region: CH
    region_mine_power: 70.74
    type: Miner

  - count: 1892
    region: US
    region_mine_power: 7.87
    type: Miner

  - count: 251
    region: RU
    region_mine_power: 7.50
    type: Miner

  - count: 5
    region: KZ
    region_mine_power: 6.71
    type: Miner

  - count: 19
    region: ML
    region_mine_power: 4.71
    type: Miner

  - count: 316
    region: CN
    region_mine_power: 0.89
    type: Miner

  - count: 1769
    region: GE
    region_mine_power: 0.61
    type: Miner

  - count: 32
    region: NR
    region_mine_power: 0.52
    type: Miner

  - count: 2
    region: VN
    region_mine_power: 0.46
    type: Miner

